package ssn.sycon.ticketing.utils;

import java.util.HashMap;
import java.util.Map;

public class Constants {
    public static final Map<Integer, String> referralCode = new HashMap<Integer,String>();
    static{
        referralCode.put(9204, "Akshat jain");
        referralCode.put(1031, "Anusharaj S");
        referralCode.put(4547, "Gunanicaa Arun");
        referralCode.put(7320, "Jiitesh S");
        referralCode.put(3830, "Khyati Gattani");
        referralCode.put(3531, "Mahalakshmi M");
        referralCode.put(1142, "Meghana Srikanth");
        referralCode.put(6532, "Naveen Raj");
        referralCode.put(3732, "Nitish kanna K");
        referralCode.put(9013, "Prashant");
        referralCode.put(8942, "Praveen subramanyam ");
        referralCode.put(9176, "R Abhinaya");
        referralCode.put(6657, "R Varshini");
        referralCode.put(6960, "Rohan Nivash");
        referralCode.put(5687, "Sharmada");
        referralCode.put(1548, "Sudhehan");
        referralCode.put(3081, "Suneeth");
        referralCode.put(8202, "Supraja Vaidhyanathan");
        referralCode.put(8586, "Thrisha");
        referralCode.put(7595, "Vandhana Vishnuraj");
        referralCode.put(3722, "Vikash Anand");
        referralCode.put(1647, "Vishnu J");
        referralCode.put(6338, "Akash P");
        referralCode.put(6351, "Akshaj Varma");
        referralCode.put(2166, "Arushi Sahu");
        referralCode.put(9042, "Ashwini ramesh");
        referralCode.put(2153, "B.Aishwarya");
        referralCode.put(2533, "Hareesh Balaji N S");
        referralCode.put(2284, "Harshini J");
        referralCode.put(1412, "Hevanthika");
        referralCode.put(2607, "Kilwish Nighjo A");
        referralCode.put(2500, "Meenaksi Venkatachalam");
        referralCode.put(8262, "Nabeel Hussain");
        referralCode.put(8096, "Sarayyu M K");
        referralCode.put(2141, "Tharunika T M");
        referralCode.put(1497, "v s kavya");
        referralCode.put(8074, "Valli");
        referralCode.put(9641, "Vasundhhara");
        referralCode.put(3214, "Vinu Abinayaa R");
        referralCode.put(3265, "Basundhara Bhattacharjee");
        referralCode.put(1956, "Dhruv kapoor");
        referralCode.put(3677, "Jaanhavi S");
        referralCode.put(1892, "Jyothir Adithya Skandan R M");
        referralCode.put(8989, "K Prabhakaran");
        referralCode.put(2027, "Kiran P");
        referralCode.put(8692, "Krish Abhishek");
        referralCode.put(1019, "Leenasri R");
        referralCode.put(6185, "Likhitha Verma");
        referralCode.put(3676, "Mohamed Vasi");
        referralCode.put(7642, "Mohanraj A");
        referralCode.put(5341, "Monisha J");
        referralCode.put(5600, "Nazir Hussain");
        referralCode.put(2738, "Nishitha Saraswathi A");
        referralCode.put(9791, "Shivaani S");
        referralCode.put(6667, "Sidharath k shah");
        referralCode.put(1847, "Srinath Venkatesh");
        referralCode.put(8446, "Susmithaa Raam");
        referralCode.put(8143, "Vasanthan R");
        referralCode.put(4680, "Venkat girisan");
        referralCode.put(8046, "Vishal T");
        referralCode.put(1788, "Viswapriya G");
        referralCode.put(2832, "HARIRAJ M J");
        referralCode.put(5934, "Ramya R");
        referralCode.put(6696, "Aravindakshan S");
        referralCode.put(7722, "Kirthik");
        referralCode.put(8189, "Dev Chaurasia");
    };
}
